INSERT INTO ID_GEN VALUES (0,'guest_id');
INSERT INTO ID_GEN VALUES (0,'stay_id');
INSERT INTO ID_GEN VALUES (0,'box_management_id');
INSERT INTO ID_GEN VALUES (0,'eq_type_id');
INSERT INTO ID_GEN VALUES (0,'eq_id');
INSERT INTO ID_GEN VALUES (0,'loan_id');
